# Use Node.js 20.13.1-alpine as the base image
FROM node:20.13.1-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the application source code
COPY . .

RUN npm run initPrisma
# Expose port 3000 for the dev server
EXPOSE 3000
RUN npm run build
# Start the development server
CMD ["npm", "start"]
