services:
  nextjs-app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: nextjs-app
    ports:
      - "80:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgresql://postgres:PAKAWAN0367@postgres:5432/sadatabase"  
    restart: always  # This will restart the app if it fails
    networks:
      default:


networks:
  default:
    external: true
    name: sa-network
