services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    ports:
      - "80:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgresql://postgres:PAKAWAN0367@postgres:5432/sadatabase"
    restart: always
    depends_on:
      - postgres
    networks:
      - sa-network  # Connect to the existing sa-network


networks:
  default:
    external: true
    name: sa-network
