services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PAKAWAN0367
      POSTGRES_DB: sadatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      default:

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      default:
volumes:
  pgdata:
  
networks:
  default:
    external: true
    name: sa-network