import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CU SERV",
  description: "Generated by create next app",
  icons: [
    { rel: "icon", url: "/favicon.png", type: "image/png" },
    { rel: "shortcut icon", url: "/favicon.ico", type: "image/x-icon" },
  ],
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" type="image/png" />
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}

